create table folders(
    folder_id integer primary key generated by default as identity,
    folder_name text not null
);

create table notes(
    note_id integer primary key generated by default as identity,
    note_name text not null,
    modified timestamptz default now(),
    folder_id integer references folders(folder_id) on delete cascade not null,
    content text not null
);